name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet sln
    - name: Install dependencies1
      run: dotnet restore ../linuxdockern.sln
    - name: Build
      run: dotnet build ../linuxdockern.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ../linuxdockern.sln --no-restore --verbosity normal
